<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-05-07T20:22:17 IST" name="Default suite" finished-at="2025-05-07T20:24:08 IST" duration-ms="111244">
    <groups>
    </groups>
    <test started-at="2025-05-07T20:22:17 IST" name="Default test" finished-at="2025-05-07T20:24:08 IST" duration-ms="111244">
      <class name="sZephyr_testcases.TC02_SignUp">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:sZephyr_testcases.TC02_SignUp@2bfc268b]" started-at="2025-05-07T20:22:17 IST" name="beforeSuite" finished-at="2025-05-07T20:22:17 IST" duration-ms="272" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:sZephyr_testcases.TC02_SignUp@2bfc268b]" started-at="2025-05-07T20:22:17 IST" name="beforeTest" finished-at="2025-05-07T20:22:17 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC02_SignUp@2bfc268b]" started-at="2025-05-07T20:22:17 IST" name="startTestCase" finished-at="2025-05-07T20:22:17 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC02_SignUp@2bfc268b]" started-at="2025-05-07T20:22:17 IST" name="beforeMethod" finished-at="2025-05-07T20:22:17 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="signUp()[pri:1, instance:sZephyr_testcases.TC02_SignUp@2bfc268b]" started-at="2025-05-07T20:22:17 IST" name="signUp" finished-at="2025-05-07T20:24:07 IST" duration-ms="110412" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[FAILED]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: FAILED
at utils.Reporter.reportStep(Reporter.java:50)
at wrappers.GenericWrappers.fail(GenericWrappers.java:994)
at sZephyr_testcases.TC02_SignUp.signUp(TC02_SignUp.java:80)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUp -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC02_SignUp@2bfc268b]" started-at="2025-05-07T20:24:07 IST" name="afterMethod" finished-at="2025-05-07T20:24:08 IST" duration-ms="801" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:sZephyr_testcases.TC02_SignUp@2bfc268b]" started-at="2025-05-07T20:24:08 IST" name="afterTest" finished-at="2025-05-07T20:24:08 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:sZephyr_testcases.TC02_SignUp@2bfc268b]" started-at="2025-05-07T20:24:08 IST" name="afterSuite" finished-at="2025-05-07T20:24:08 IST" duration-ms="225" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- sZephyr_testcases.TC02_SignUp -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
